# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
sudo: true
python:
  - "3.6"
sudo: required
env:
  - DATABASE=DUMMY

cache:
  directories:
    - eggs
install:
  - sudo rm -f /etc/boto.cfg
  - pip install -e .[test]
  - pip install -r dev-requirements.txt
  - pip install flake8 codecov pytest-cov
before_script:
  - python3 -m moto.server -H 127.0.0.1 -p 5000 s3 &
  - sleep 10
script:
    - flake8 guillotina_s3storage --config=setup.cfg
    - pytest -s --cov=guillotina_s3storage -s --tb=native -v --cov-report term-missing --cov-append ./guillotina_s3storage
after_success:
  - codecov
