# we want to make sure it is run on trusty where sudo is provided for postgres
dist: trusty
language: python
python:
  - "3.6"
sudo: required
env:
  - DATABASE=DUMMY

cache:
  directories:
    - eggs
install:
  - pip install -e .[test]
  - pip install -r dev-requirements.txt
  - pip install flake8 codecov
  - sleep 5
script:
    - flake8 guillotina_s3storage --config=setup.cfg
    - pytest -s --cov=guillotina_s3storage -s --tb=native -v --cov-report term-missing --cov-append guillotina_s3storage
after_success:
  - codecov
